# Generated by Django 3.2.18 on 2023-03-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
