# Generated by Django 3.2.18 on 2023-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20230323_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='state',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='street',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
