# Generated by Django 3.2.18 on 2023-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
